# Generated by Django 5.0.3 on 2025-12-11 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('type_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('machine_id', models.CharField(editable=False, max_length=45, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.machinetype')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.machines')),
            ],
        ),
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_machine', to='api.users')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_user', to='api.users')),
            ],
        ),
    ]
